In [4]:
daily_kwh = [400,500,600,700,800,900,800,700,600,500]
total_energy = sum(daily_kwh)
print("Total energy used:",total_energy,"kwh")

Total energy used: 6500 kwh

In [5]:
Building_usage = {
    "AIML":800,
    "CIVIL":500
}
print("CIVIL used: ",Building_usage["CIVIL"],"kwh")

CIVIL used:  500 kwh

In [6]:
# program 3: a function to calculate electricity cost
def calculate_bill(kwh, rate_per_unit):
   return kwh * rate_per_unit

today_bill = calculate_bill(600, 3)
print("Today's estimated bill is Rs.", today_bill)

Today's estimated bill is Rs. 1800

In [7]:
with open("campus_energy.csv", "r") as file:
  for line in file.readlines():
     print(line.strip())

﻿Date ,Building,kwh/used,peak hour usage
05-10-2026,CSE,400,210
06-10-2026,CIVIL,500,220
07-10-2026,ECE,600,230
08-10-2026,CSE,700,240
09-10-2026,ECE,800,250
10-10-2026,ECE,900,260
11-10-2026,AIML,800,270
12-10-2026,AIDS,700,280
13-10-2026,IOT,600,290
14-10-2026,CYBER,500,300

In [17]:
# import the pandas library
import pandas as pd

# load the dataset you created
df = pd.read_csv("campus_energy.csv")

# display the first few rows of the data
print("Here is the raw data:")
display(df.head())

# Group the data to see total usage per building (fixed column names)
building_totals = df.groupby("Building")["kwh/used"].sum()
print("\nTotal usage per building:")
print(building_totals)

# Generate a statistical summary of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

        Date  Building  kwh/used  peak hour usage
0  05-10-2026      CSE       400              210
1  06-10-2026    CIVIL       500              220
2  07-10-2026      ECE       600              230
3  08-10-2026      CSE       700              240
4  09-10-2026      ECE       800              250

Total usage per building:
Building
AIDS      700
AIML      800
CIVIL     500
CSE      1100
CYBER     500
ECE      2300
IOT       600
Name: kwh/used, dtype: int64

Statistical Summary:

         kwh/used  peak hour usage
count   10.000000        10.000000
mean   650.000000       255.000000
std    158.113883        30.276504
min    400.000000       210.000000
25%    525.000000       232.500000
50%    650.000000       255.000000
75%    775.000000       277.500000
max    900.000000       300.000000

In [18]:
# create the README.md file and write a message inside it

with open("README.md", "w") as file:
  file.write("# Smart Campus Energy project\n")
  file.write("This repository contains My week 1 hands-on Python and pandas assignments:\n")
  file.write("created by: [Chaitanya]")

  print("README.md has been successfully created")

README.md has been successfully created